import re

normalizer = re.compile(r'[^\dA-Z&\s]')
whitespace = re.compile(r'[\s+]')

def normalize_category_name(s):
    return whitespace.sub(' ', normalizer.sub('', s.strip().upper().replace('&AMP;', '&')))

METACATEGORIES = { 'SCIENCE': [ 
    'PHYSICS',
    'THE SENSES',
    'BIRDS',
    'BIOLOGY',
    'GEMS',
    'ANIMALS',
    'THE BODY HUMAN',
    'CONSTELLATIONS',
    'PLANTS',
    'TECHNOLOGY',
    'MAMMALS',  
],
'BUSINESS': [
    'MUSIC BUSINESS',
    'BUSINESS & INDUSTRY',
    'CORPORATE AMERICA',
    'MONEY',    
],
'RELIGION': [
    'YE GODS',
    'THE BIBLE',
    'RELIGION',
],
'ARTS': [
    'POETIC TERMS',
    'FICTIONAL CHARACTERS',
    '20TH CENTURY POETRY',
    'HISTORICAL DRAMAS',
    'SHAKESPEAREAN TRIVIA'
],
'POP CULTURE': [
    'MR MOVIES',
    'STORYTELLERS',
    'THE HUSBAND MARRIED',
    'TOUGH TV TRIVIA',
    'THE OLYMPICS',
    'STARRY SONGS',
    'TV COMMERCIALS',
    'SPORTS STADIUMS',
    '60S BRITISH ROCK',   
    'MOVIE AUTHORS',
    'SPORTS',
    'FASHION',
    'LYRICS',
    'ACTORS & ROLE',
    'TV CAPTAINS',  
    'SILLY SONGS',      
],
'GEOGRAPHY': [
    'NEIGHBORHOODS',
    'WORLD CAPITALS',
    'WORLD GEOGRAPHY',
    'ISLANDS',
    'LAKES & RIVERS', 
    'AMERICAN RIVERS',
    'US STATES',
    'EUROPE',   
    'NEPAL',       
    'ARKANSAS',       
    'MEMPHIS',    
],
'HISTORY': [
    'APOLLO 11',
    'ANCIENT VIPS',    
    'PRESIDENTS',
    'GREAT DAMES',
    'WORLD WAR II',
    'COLONIAL AMERICA',
    'ROYALTY',
    'REVOLUTIONARY WAR',
    'DYNASTIES',
    'NATIVE AMER WOMEN',
    'INDIANS',
    'FIRST LADIES',
    '1946', 
    'DEMOCRATS',
],
'WORDPLAY': [
    'STARS WITH C',
    'STARTS WITH P',
    'WORDS',
    'LETTER PERFECT',
    '13LETTER WORDS',
    'AC',
    'DC',
    'NAMES THE SAME',
    'HOMOPHONIC PAIRS',    
],
'MISC': [
    'MEATS',
    'THE MAIN INGREDIENT',
    'NEWSPAPERS',
    'TRANSPORTATION',
    'SUMMER',
    'AUTOMOBILES',
    'LESSERKNOWN NAMES',
    'GOING IN STYLE',
    'AKA',
    'FAMOUS QUOTES',
    'HOLIDAYS',

] }